profiles = {
  "BADGIRLCOVEN": ["Owl Lady", "Owl Shack", "Scab. 2017", "Formerly wanted criminal, now Headmaster at @UWM", "12", "31.4k"],
  "goo-daddy": ["Darius D.", "noyb", "Jaw. 2017", "Abominations > People", "35", "20.6k"],
  "rainey.day": ["Raine Whispers", "The Owl House", "Fea. 2020", "Hello!", "1", "16.3k"],
  "goodWitchLuzura": ["<i>✨🌟Luz🌟✨</i>", "Flip-flopping CT and the BI", "Jaw. 2021", 
  "Sweet Potato of @WitchChick128<br/> @veeeeeee's sister.<br/>the reports of my death were minorly exaggerated", "73", "98k"],
  "goops": ["Gus Porter", "UWM Branch 19", "Sep. 2017", "Founder of the DR-HR Exchange Program", "306", "1.5k"],
  "em_ira": ["The Older Blight Twin", "Your Mom's Bedroom", "Parch 2016", "<i>Waiting for mom to kick the bucket so I can let her down one last time.</i>", "305", "4.8k"],
  "bestBlight": ["Ed", "Rent-free in your head", "Parch 2016", "Doing stupid things so you don't have to. SUBCRIBE TO MY MEWTUBE OR ELSE.", "478", "11.3k"],
  "WitchChick128": ["Mittens", "Bonesborough", "Ath. 2017", "Sweet potato of @goodWitchLuzura <br/>Younger sibling of @em_ira and @bestBlight.", "289", "19k"],
  "veeeeeee": ["Vee Noceda (she/her)", "La Casa Noceda", "Dis. 2021", "Sometimes a snake, sometimes a human, always adorable.<br/>Sister of @goodWitchLuzura", "51", "6.2k"],
  "MashPit": ["Masha (they/them)", "Gravesfield, CT", "Dis. 2021", "Ich weiss nicht, etwas auf Deutsch.<br/> Partner of @veeeeeee Noceda", "9", "428"],
  "HOOOOOOOOOT": ["hootsifer", "Papa Titan's Eye Socket", "The Dawn of Time", "there is no beginning. there is no end. there is only hoot.", "-1", "Infinite"],
  "chilly.lily": ["Lilith Clawthorne", "Clavicus, Left Arm", "Scab. 2018", "Lead Historian at @SNMH | Occasional ink connoisseur", "51", "21.7k"],
  "SNMH": ["The Supernatural Museum of History", "200 W. Bronchial Rd.", "Saw. 2021", "Where history comes to life! Lead historian: @chilly.lily", "10", "15k"],
  "RAISEDBYDIREWOLVES": ["Eberwolf the Huntsman", "Yes", "Dis. 2019", ">:3", "2", "31"],
  "RULERZREACHF4N": ["Hunter Park-Deamonne-Noceda-Clawthorne-Whispers", "carving palismen", "Awk. 2021", "R.I.P Flapjack - Thank you for finding me.", "5", "5.1K"],
  "Hello_willow": ["Willow Park", "Bonseborough, The Chest", "Scab. 2019", "Captain of the @EmeraldEntrails, Hexside Class of '22.", "17", "30.4k"],
  "UWM": ["<i>The</i> University of Wild Magic", "The Tree", "Fea. 2022", "Official account of the University of Wild Magic, the only college worth a hoot. Home of the Owls.", "62", "32k"],
  "EmeraldEntrails": ["The Sea of Green", "The Pitch", "Gna. 2021", "The OFFICIAL account for the Emerald Entrails Flyer Derby Team. Captained by @Hello_willow", "5", "21k"],
  "Alabomdor_1": ["AD", "Humerusstadt", "Fea. 2017", "Rat dad | Formerly of Blight Industries", "83", "25.1k"],
  "FreeTheLemons": ["Lemons aka Katya (she/her)", "posting fic on OFW", "Dis. 2017", "writer and storyteller | drinking the tears of my readers", "849", "11.3k"],
  "skara4real": ["scare bear enthusiast", "a hole", "Fea. 2018", "flyer derby for the @EmeraldEntrails.", "285", "2.3k"],
  "_derwin": ["derwin", "no", "Fea. 2019", "Bard magic is cool.", "581", "403"],
  "bo-lieve": ["Bo Jangles", "movin'", "Fea. 2018", "I know. do you?", "69", "386"],
  "amberamberamber": ["giraffe truther", "in denial", "Dis. 2019", "she/her | i am cringe, but i am free", "314", "15.9k"],
  "steve": ["The Best Character In The Show", "My Heart", "Awk. 2020", "My love language is shoulder pats.", "1", "TREE(3)"],
  "KINGOFDEMONS": ["KC", "My Dad's Corpse", "Awf. 2021", "Squirmy lil fella trying to fill some titan-sized shoes.", "2", "68k"],
  "Hexside": ["Hexside School of Magic and Demonics", "S. 314 Ligament Lane", "Awk. 2012", "The official account for the one and only Hexside School of Magic and Demonics. Go Banshees!", "42", "2.7k"],
  "HexsideFreePress": ["Hexside Free Press", "Hexside", "Fea. 2018", "The premier news source for everything going down in Banshee Country.", "9", "473"],
  "BBC": ["Boiling Broadcast Corporation", "CB, Online 24/7", "Jaw. 2009", "The BBC is the Isle's leading public service broadcaster.", "108", "53k"],
  "TheDailyDirt": ["The Daily Dirt", "The Streets", "Awk. 2016", "Real news for real people.", "0", "14k"],
  "MARILYN.PLEASE.COME.BACK": ["", "Gravity Falls, OR", "Sep. 2023", "", "0", "0"],
  "I.MISS.YOU": ["", "Gravity Falls, OR", "Sep. 2023", "", "0", "0"],
  "stan": ["Stan Pines", "Gravity Falls, OR", "Sep. 2023", "grunkle", "0", "0"],
  "WardenWrath": ["Wrath", "Bonesborough", "Auf. 2020", "I love two things: my adorable baby boy and listening to the screams of the damned.", "1", "13"],
  "bigN0s3": ["Tinella Nosa", "Nosa Publishing House", "Fea. 2018", "BUY MY STOWY OR FACE MY WATH (ONLY 20 SNAILS!)", "841", "68.6k"],
  "41.6C.69.65.6E.73.46.72.6F.6D.4D.61.72.73": ["54 68 65 20 41 6C 69 65 6E 73", "4D 61 72 73", "Saw. 2021", "47 49 56 45 20 55 53 20 59 4F 55 52 20 54 45 45 54 48", "0", "1"],
  "GlandusGazette": ["The Glandus Gazette", "Glandus High", "Awk. 2020", "Here", "18", "472"],
  "BINN": ["Boiling Isles News Network", "The Pulse of the Isles", "Awk. 2012", "Live News 24/7 on CB Channel 7", "23", "41k"],
  "PerryPorter": ["Perry Porter", "On The Scene", "Dis. 2014", "Reporter for @BINN", "209", "14k"],
}
