profiles = {
  "BADGIRLCOVEN": ["Owl Lady", "Owl Shack", "Scab. 2017", "Formerly wanted criminal, now Headmaster at @UWM", "12", "31.4k"],
  "goo-daddy": ["Darius D.", "noyb", "Jaw. 2017", "Abominations > People", "35", "20.6k"],
  "rainey.day": ["Raine Whispers", "The Owl House", "Fea. 2020", "Hello!", "1", "16.3k"],
  "goodWitchLuzura": ["<i>Luz</i>", "Flip-flopping CT and the BI", "Jaw. 2021", 
  "Sweet Potato of @WitchChick128<br/> @veeeeeee's sister.<br/>the reports of my death were minorly exaggerated", "73", "98k"],
  "goops": ["Gus Porter", "UWM Branch 19", "Sep. 2017", "Founder of the DR-HR Exchange Program", "306", "1.5k"],
  "em_ira": ["The Older Blight Twin", "Your Mom's Bedroom", "Parch 2016", 
             "<i>Waiting for mom to kick the bucket so I can let her down one last time.</i>", "305", "4.8k"],
  "bestBlight": ["Ed", "Rent-free in your head", "Parch 2016", "Doing stupid things so you don't have to. SUBCRIBE TO MY MEWTUBE OR ELSE.", "478", "11.3k"],
  "WitchChick128": ["Mittens", "Bonesborough", "Ath. 2017", "Sweet potato of @goodWitchLuzura <br/>Younger sibling of @em_ira and @bestBlight.", "289", "19k"],
  "veeeeeee": ["Vee Noceda (she/her)", "La Casa Noceda", "Dis. 2021", "Sometimes a snake, sometimes a human, always adorable.<br/>Sister of @goodWitchLuzura", "51", "6.2k"],
  "MashPit": ["Masha (they/them)", "Gravesfield, CT", "Dis. 2021", "Ich weiss nicht, etwas auf Deutsch.<br/> Partner of @veeeeeee Noceda", "9", "428"],
  "HOOOOOOOOOT": ["hootsifer", "Papa Titan's Eye Socket", "The Dawn of Time", "there is no beginning. there is no end. there is only hoot.", "-1", "Infinite"],
  "chilly.lily": ["Lilith Clawthorne", "Clavicus, Left Arm", "Scab. 2018", "Lead Historian at @SNMH | Occasional ink connoisseur", "51", "21.7k"],
  "SNMH": ["The Supernatural Museum of History", "200 W. Bronchial Rd.", "Saw. 2021", "Where history comes to life! Lead historian: @chilly.lily", "10", "15k"],
  "RAISEDBYDIREWOLVES": ["Eberwolf the Huntsman", "Yes", "Dis. 2019", ">:3", "2", "31"],
  "RULERZREACHF4N": ["Hunter Park-Deamonne-Noceda-Clawthorne-Whispers", "carving palismen", "Awk. 2021",
                     "R.I.P Flapjack - Thank you for finding me.", "5", "5.1K"],
  "Hello_willow": ["Willow Park", "Bonseborough, The Chest", "Scab. 2019", "Captain of the @EmeraldEntrails, Hexside Class of '22.", "17", "30.4k"],
  "UWM": ["<i>The</i> University of Wild Magic", "The Tree", "Fea. 2022", "Official account of the University of Wild Magic, the only college worth a hoot. Home of the Owls.", "62", "32k"],
  "EmeraldEntrails": ["The Sea of Green", "The Pitch", "Gna. 2021", "The OFFICIAL account for the Emerald Entrails Flyer Derby Team. Captained by @Hello_willow", "5", "21k"],
  "Alabomdor_1": ["AD", "Humerusstadt", "Fea. 2017", "Rat dad | Formerly of Blight Industries", "83", "25.1k"],
  "FreeTheLemons": ["Lemons aka Katya (she/her)", "posting fic on OFW", "Dis. 201p", "writer and storyteller | drinking the tears of my readers", "849", "11.3k"],
  "skara4real": ["scare bear enthusiast", "a hole", "Fea. 2018", "flyer derby for the @EmeraldEntrails.", "285", "2.3k"],
  "_derwin": ["derwin", "no", "Fea. 2019", "Bard magic is cool.", "581", "403"],
  "bo-lieve": ["Bo Jangles", "movin'", "Fea. 2018", "I know. do you?", "69", "386"],
  "amberamberamber": ["giraffe truther", "in denial", "Dis. 2019", "she/her | i am cringe, but i am free", "314", "15.9k"],
  "steve": ["The Best Character In The Show", "My Heart", "Awk. 2020", "My love language is shoulder pats.", "1", "TREE(3)"],
  "KINGOFDEMONS": ["KC", "My Dad's Corpse", "Awf. 2021", "Squirmy lil fella trying to fill some titan-sized shoes.", "2", "68k"],
}
