feeds = {
  "eda": [
    ["BADGIRLCOVEN", "10:09 AM", "Third mug of appleblood downed. Time to rob some schmucks blind."],
    ["rainey.day", "10:11 AM", "Eda, you realize these are monitored, right?"],
    ["BADGIRLCOVEN", "10:12 A M", "don't care."],
    ["goodWitchLuzura", "11:26 AM", "amity ur so pretty"],
    ["goops", "12:03 PM", "Finally changed my display name so people know who I am."],
    ["goodWitchLuzura", "12:19 PM", "@em_ira @bestBlight which one of you stoll my scroll? - Amity"],
    ["em_ira", "12:20 PM", "We'll give it back if you promise not to tell Dad that we snuck out to meet Jerbo and Viney."],
    ["goodWitchLuzura", "12:20 PM", "I wouldn't do that, anyway. - Amity"],
    ["bestBlight", "12:21 PM", "hey mittens, catch lol"],
    ["WitchChick128", "12:22 PM", "Thank you."],
    ["veeeeeee", "12:25 PM", ":3"],
    ["MashPit", "12:25 PM", "Nearly got eaten a few minutes ago, but fought em off. RIP bozo, never stood a chance."],
    ["BADGIRLCOVEN", "12:26 PM", "y do i keep getting notis from all you kids."],
    ["BADGIRLCOVEN", "12:28 PM", "screw this time for apple blood #4."],
    ["HOOOOOOOOOT", "6:66 PM", "SOULS OF THE DAMNED ARE YUMMY HOOT HOOT"],
  ],
  "darius": [
    ["goo-daddy", "9:21 AM", "Never trust a man who says a dead body is talking to him and him alone. Unless it's me. Always trust me."],
    ["rainey.day", "9:35 AM", "Just had a very relaxing tea with my breakfast. Time to start the day!"],
    ["RAISEDBYDIREWOLVES", "10:21 AM", "saw a cool rock :)"],
    ["RULERZREACHF4N", "11:07 AM", "h0w .aer yoi gyus sp good at tyipng"],
    ["Hello_willow", "11:07 AM", "You'll get better with time, Hunnybun."],
    ["RULERZREACHF4N", "11:09 AM", "thanks, Captain"],
    ["chilly.lily", "11:30 AM", "New ink review dropping tomorrow!"],
    ["rainey.day", "11:36 AM", "I want to try something."],
    ["rainey.day", "11:38 AM", "01001111 01001000 00100000 01010100 01001001 01010100 01000001 01001110 00100000 01010100 01001000 01001001 01010011 00100000 01001001 01010011 00100000 01000001 01010111 01000110 01010101 01001100"],
    ["rainey.day", "11:40 AM", "Never doing that again."],
    ["Alabomdor_1", "12:00 PM", "The divorce is official."],
    ["goo-daddy", "12:01 PM", "@Alabomdor_1 O'Malley's to celebrate?"],
    ["Alabomdor_1", "12:02 PM", "@goo-daddy Yes please."],
    ["goo-daddy", "2:47 PM", "In 17 years of existence, @RULERZREACHF4N still has not gained a sense of what is fashionable. That will have to be remedied one of these days."],
    ["Alabomdor_1", "2:49 PM", "I hope she-who-must-not-be-named rots for what she did."],
    ["chilly.lily", "2:50 PM", "Oh no. Don't tell me."],
    ["Alabomdor_1", "2:52 PM", "Don't be the fun police @chilly.lily :( drunk words, sober thoughts, ya know?"],
    ["goo-daddy", "2:52 PM", "Please don't engage with this hack. Leave that to me."],
    ["Alabomdor_1", "2:52 PM", "i wouldnt mind being engaged to you @goo-daddy"],
    ["chilly.lily", "2:53 PM", "Titan have mercy. This is a public forum and you two are clearly intoxicated."],
    ["Alabomdor_1", "2:55 PM", "y dont you join us @chilly.lily ????"],
    ["chilly.lily", "2:56 PM", "@Alabomdor_1 No."],
    ["Alabomdor_1", "2:56 PM", "@chilly.lily Please?"],
    ["chilly.lily", "2:57 PM", "@Alabomdor_1 Not a chance."],
    ["Alabomdor_1", "2:57 PM", "@chilly.lily Please."],
    ["Alabomdor_1", "2:58 PM", "@chilly.lily Please."],
    ["goo-daddy", "2:58 PM", "Stop spamming."],
    ["Alabomdor_1", "2:59 PM", "@chilly.lily Pretty please?"],
    ["Alabomdor_1", "3:00 PM", "@chilly.lily Please. Please. Please. <i>Pleeeeaseeee?</i> I'll stop if you buy something."],
    ["chilly.lily", "3:01 PM", "@Alabomdor_1 Fine. I'll come over. Give me a few minutes."],
    ["goo-daddy", "4:20 PM", "Mistakes are being made. Fun mistakes, but mistakes nonetheless."],
    ["chilly.lily", "4:34 PM", "I now see why @BADGIRLCOVEN likes apple blood so much."],
    ["goo-daddy", "5:36 PM", "@BADGIRLCOVEN Can you come pick up your sister? She's downed at least twelve shots of firebee whiskey and is currently trying to use the refrigerator as a time machine."],
    ["chilly.lily", "5:39 PM", "I NEED TO GO BACK SO I CAN KICK THAT NO GOOD EXCUSE FOR A HUMAN IN HIS NO NO SQUARE! A BROKEN NOSE IS NOT ENOUGH! HE MUST <i>PAY</i>!"],
    ["chilly.lily", "6:41 PM", "evrythng is wonky and funny olored."],
    ["chilly.lily", "6:42 PM", "im sleppy. couchll do nice."],
    ["RAISEDBYDIREWOLVES", "8:06 PM", "Stole a not dog from Snapdragon. ^_^"],
  ],
  "raine": [
    ["rainey.day", "2:07 AM", "Just did a line of rosin powder. Let's get this money, bards."],
    ["skara4real", "8:24 AM", "Hot Take: Violas are better than violins in every aspect."],
    ["_derwin", "8:27 AM", "@skara4real lmao wrong. Bassoons are obviously the best. Violin and viola are just battling for 2nd."],
    ["FreeTheLemons", "8:30 AM", "@_derwin @skara4real You are both wrong. Theremin is indubitably the coolest."],
    ["_derwin", "8:30 AM", "@FreeTheLemons Wow, I can't believe you actually know the word 'indubitably.'"],
    ["FreeTheLemons", "8:32 AM", "@_derwin Verily, my vast vocabulary vastly vindicates my verbal virtuosity, verifying my verbose volubility."],
    ["_derwin", "8:33 AM", "@FreeTheLemons bro what"],
    ["FreeTheLemons", "8:34 AM", "@_derwin I write fic, so I constantly use a thesarus to ensure that I don't repeat words, which means I also learn a lot of new words in the process."],
    ["skara4real", "8:36 AM", "all this because I said that violas are better. (still true, btw.)"],
    ["bo-lieve", "9:41 AM", "Yo, @goops, can I get an expedited review for my DR-HR Exchange Program appliaction?"],
    ["goops", "9:43 AM", "Yeah, I can probably pull some strings @bo-lieve"],
    ["bo-lieve", "9:44 AM", "@goops thx"],
    ["goops", "9:44 AM", "No biggie @bo-lieve"],
    ["rainey.day", "10:03 AM", "Alongside music, I also dreamed of being an actor."],
    ["rainey.day", "10:04 AM", "But then <i>it</i> happened."],
    ["rainey.day", "10:05 AM", "I still get nightmares about that day."],
    ["FreeTheLemons", "10:07 AM", "@rainey.day How many snails for you to the Monarch In Orange?"],
    ["rainey.day", "10:08 AM", "None, cause I'm never doing that cursed production. I enjoy having my soul inside my body, thank you very much."],
    ["FreeTheLemons", "10:08 AM", "@rainey.day :( ur no fun"],
    ["amberamberamber", "12:19 AM", "if @BADGIRLCOVEN is our mom, does that make @KINGOFDEMONS our brother???"],
    ["BADGIRLCOVEN", "12:22 AM", "That's not how that works, kid. Like, at all."],
    ["BADGIRLCOVEN", "12:22 AM", "Also, I'm not even your mom, technically. Raine and I haven't tied the knot yet, and probably never will."],
    ["amberamberamber", "12:24 AM", "dang, I thought that would be cool to brag about."],
    ["BADGIRLCOVEN", "12:25 AM", "Yeah, well that's the way the spookie crumbles sometimes."],
    ["BADGIRLCOVEN", "2:17 AM", "WHERE THE <i><b>HOOT</b></i> DID MY APPLE BLOOD GO?!"],
    ["steve", "3:00 AM", "steve."],
  ],
  "luz": [
    ["goodWitchLuzura", "10:03 AM", "Good morning, Penstagram! (*^▽^*)"],
    ["veeeeeee", "10:05 AM", "yo yo welcome to Pensta, sis."],
    ["goodWitchLuzura", "10:06 AM", "how did you get a scroll before me lol"],
    ["veeeeeee", "10:06 AM", "big sister magic. don't question it."],
    ["goodWitchLuzura", "10:07 AM", "pretty sure I'm older but ok"],
    ["goodWitchLuzura", "10:07 AM", "hold on... how old are you, @veeeeeee?"],
    ["veeeeeee", "10:08 AM", "uh... however old you are + 1"],
    ["goodWitchLuzura", "10:09 AM", "(ㆆ_ㆆ) that's not an answer"],
    ["veeeeeee", "10:10 AM", "best you're getting lol."],
    ["goodWitchLuzura", "10:13 AM", "<img src='images/secrets.gif' class='pm_image'>"],
  ],
}
